/**
 * ~200 common freelance roles — non-forcing `<datalist>` suggestions.
 * The user can always type something that isn't in this list.
 * Grouped by domain for easy maintenance, flattened for the datalist.
 */
export const SKILL_SUGGESTIONS: string[] = [
  // ── Design ───────────────────────────────────────────────
  "Brand designer",
  "Logo designer",
  "Graphic designer",
  "UI designer",
  "UX designer",
  "Product designer",
  "Web designer",
  "Mobile app designer",
  "Interaction designer",
  "Design systems designer",
  "Illustrator",
  "Motion designer",
  "3D designer",
  "Typography designer",
  "Packaging designer",
  "Print designer",
  "Editorial designer",
  "Exhibition designer",
  "Industrial designer",
  "Automotive designer",
  "Furniture designer",
  "Jewelry designer",
  "Textile designer",
  "Fashion designer",
  "Costume designer",
  "Surface pattern designer",
  "Icon designer",
  "Presentation designer",
  "Pitch deck designer",
  "Infographic designer",
  "Email template designer",
  "Newsletter designer",
  "Magazine designer",
  "Book cover designer",
  "Album cover designer",
  "Merchandise designer",
  "Sticker designer",
  "Decal designer",
  "Signage designer",
  "Wayfinding designer",

  // ── Video, film & animation ─────────────────────────────
  "Video editor",
  "Videographer",
  "Film director",
  "Cinematographer",
  "Colorist",
  "Animator",
  "2D animator",
  "3D animator",
  "Stop-motion animator",
  "Explainer video producer",
  "After effects artist",
  "VFX artist",
  "Compositor",
  "Sound designer",
  "Foley artist",
  "Podcast producer",
  "Podcast editor",
  "Voice actor",
  "Video producer",
  "Documentary filmmaker",

  // ── Writing & content ───────────────────────────────────
  "Copywriter",
  "Content writer",
  "SEO writer",
  "Technical writer",
  "Grant writer",
  "Speechwriter",
  "Ghostwriter",
  "Blog writer",
  "Article writer",
  "Newsletter writer",
  "Social media writer",
  "UX writer",
  "Scriptwriter",
  "Screenwriter",
  "Playwright",
  "Editor",
  "Proofreader",
  "Fact-checker",
  "Translator",
  "Interpreter",
  "Subtitler",
  "Captioner",
  "Localizer",
  "Transcriptionist",

  // ── Marketing & growth ──────────────────────────────────
  "Digital marketer",
  "Growth marketer",
  "Performance marketer",
  "Email marketer",
  "Lifecycle marketer",
  "Social media manager",
  "Community manager",
  "Influencer manager",
  "Affiliate manager",
  "PPC specialist",
  "Google Ads specialist",
  "Meta Ads specialist",
  "TikTok Ads specialist",
  "LinkedIn Ads specialist",
  "SEO specialist",
  "ASO specialist",
  "Content strategist",
  "Brand strategist",
  "Brand consultant",
  "PR consultant",
  "Press release writer",
  "Event marketer",
  "CRO specialist",
  "Marketing automation specialist",
  "HubSpot specialist",
  "Marketo specialist",

  // ── Web & frontend development ──────────────────────────
  "Frontend developer",
  "React developer",
  "Next.js developer",
  "Vue developer",
  "Nuxt developer",
  "Svelte developer",
  "Angular developer",
  "Webflow developer",
  "Framer developer",
  "WordPress developer",
  "Shopify developer",
  "Wix developer",
  "Squarespace developer",
  "HTML/CSS developer",
  "JavaScript developer",
  "TypeScript developer",
  "WebGL developer",
  "Three.js developer",
  "Email developer",
  "Progressive web app developer",

  // ── Backend & full-stack development ────────────────────
  "Backend developer",
  "Full-stack developer",
  "Node.js developer",
  "Python developer",
  "Django developer",
  "Flask developer",
  "FastAPI developer",
  "Ruby on Rails developer",
  "PHP developer",
  "Laravel developer",
  "Java developer",
  "Kotlin developer",
  "Go developer",
  "Rust developer",
  "C# developer",
  ".NET developer",
  "Scala developer",
  "Elixir developer",
  "Golang developer",

  // ── Mobile development ──────────────────────────────────
  "iOS developer",
  "Swift developer",
  "Android developer",
  "Kotlin Android developer",
  "React Native developer",
  "Flutter developer",
  "Xamarin developer",
  "Mobile app developer",

  // ── Data, AI & ML ───────────────────────────────────────
  "Data scientist",
  "Data analyst",
  "Data engineer",
  "Big data engineer",
  "Machine learning engineer",
  "Deep learning engineer",
  "NLP engineer",
  "Computer vision engineer",
  "MLOps engineer",
  "AI engineer",
  "LLM engineer",
  "Prompt engineer",
  "AI consultant",
  "Chatbot developer",
  "RAG developer",
  "Statistical analyst",
  "Quantitative analyst",
  "Business intelligence analyst",
  "Power BI developer",
  "Tableau developer",

  // ── DevOps, cloud & infra ───────────────────────────────
  "DevOps engineer",
  "Site reliability engineer",
  "Cloud engineer",
  "AWS engineer",
  "Azure engineer",
  "GCP engineer",
  "Kubernetes engineer",
  "Docker specialist",
  "Terraform engineer",
  "Infrastructure engineer",
  "Platform engineer",
  "Security engineer",
  "Penetration tester",
  "Smart contract auditor",
  "Blockchain developer",
  "Solidity developer",
  "Web3 developer",

  // ── QA, testing & DBA ───────────────────────────────────
  "QA engineer",
  "Manual tester",
  "Automation tester",
  "Cypress tester",
  "Selenium tester",
  "Playwright tester",
  "Load tester",
  "Database administrator",
  "DBA",
  "SQL developer",
  "PostgreSQL developer",
  "MySQL developer",
  "MongoDB developer",
  "Supabase developer",
  "Firebase developer",

  // ── Product, project & agile ────────────────────────────
  "Product manager",
  "Technical product manager",
  "Product owner",
  "Project manager",
  "Scrum master",
  "Agile coach",
  "Program manager",
  "Delivery manager",
  "Operations manager",
  "Chief of staff",

  // ── Business, finance & legal ───────────────────────────
  "Business analyst",
  "Management consultant",
  "Strategy consultant",
  "Financial analyst",
  "Financial modeler",
  "Bookkeeper",
  "Accountant",
  "Tax consultant",
  "Virtual CFO",
  "Fractional CFO",
  "Fractional COO",
  "Data entry specialist",
  "Legal consultant",
  "Contract lawyer",
  "Privacy consultant",
  "GDPR consultant",
  "Compliance consultant",
  "Grant researcher",

  // ── Audio & music ───────────────────────────────────────
  "Music producer",
  "Audio engineer",
  "Mixing engineer",
  "Mastering engineer",
  "Composer",
  "Songwriter",
  "Session musician",
  "Guitarist",
  "Pianist",
  "Drummer",
  "Vocalist",
  "Beatmaker",

  // ── Photography ─────────────────────────────────────────
  "Photographer",
  "Product photographer",
  "Portrait photographer",
  "Wedding photographer",
  "Event photographer",
  "Real estate photographer",
  "Food photographer",
  "Fashion photographer",
  "Photo editor",
  "Retoucher",

  // ── Art & illustration ──────────────────────────────────
  "Concept artist",
  "Storyboard artist",
  "Character designer",
  "Environment artist",
  "Matte painter",
  "Comic artist",
  "Fine artist",
  "Portrait artist",
  "Caricature artist",
  "Tattoo designer",

  // ── Architecture & interior ─────────────────────────────
  "Architect",
  "Interior designer",
  "Landscape architect",
  "Urban planner",
  "3D architectural visualizer",
  "CAD drafter",
  "BIM modeler",
  "Kitchen designer",
  "Bathroom designer",

  // ── Education & coaching ────────────────────────────────
  "Tutor",
  "Online course creator",
  "Instructional designer",
  "Curriculum developer",
  "Corporate trainer",
  "Language teacher",
  "Music teacher",
  "Career coach",
  "Business coach",
  "Life coach",
  "Writing coach",

  // ── Admin & support ─────────────────────────────────────
  "Virtual assistant",
  "Executive assistant",
  "Customer support agent",
  "Customer success manager",
  "Technical support specialist",
  "Helpdesk agent",
  "Recruiter",
  "Technical recruiter",
  "HR consultant",
  "Onboarding specialist",
];
