import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";

/**
 * robots.txt — generated by Next.js.
 *
 * Indexable: /, /guides, /guides/*, /r, /privacy, /terms, /contact. Report
 * pages (/r/*) are share-by-link and noindex (each sets its own robots meta).
 * The secret diagnostics backdoor and the API are disallowed entirely.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/r/", "/rf-diag-9f2k", "/api/"],
      },
      // Explicitly allow social crawlers to fetch /r/* for link previews,
      // even though the pages carry noindex — previews still work.
      {
        userAgent: ["Googlebot", "Bingbot", "Twitterbot", "facebookexternalhit", "LinkedInBot", "Slackbot", "Discordbot"],
        allow: "/",
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
