import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";
import { getAllGuides } from "@/lib/guides";

/**
 * sitemap.xml — generated by Next.js.
 *
 * Indexable routes:
 *  - / (homepage)
 *  - /r (rate reports landing page)
 *  - /guides + every /guides/{slug} article
 *  - /privacy, /terms, /contact (legal pages)
 *
 * Report pages /r/{id} are share-by-link and `noindex,nofollow`, so they are
 * deliberately excluded from the sitemap.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const staticRoutes: MetadataRoute.Sitemap = [
    { url: `${SITE_URL}/`, lastModified: now, changeFrequency: "weekly", priority: 1 },
    { url: `${SITE_URL}/r`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${SITE_URL}/guides`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${SITE_URL}/privacy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE_URL}/terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE_URL}/contact`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
  ];
  // Add every guide article.
  const guides = getAllGuides().map((g) => ({
    url: `${SITE_URL}/guides/${g.slug}`,
    lastModified: new Date(g.updated),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));
  return [...staticRoutes, ...guides];
}
